Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA A800-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Using 26969/269695 training samples (10.0%)
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py:231: Precision 16-mixed is not supported by the model summary.  Estimated model size in MB will not be accurate. Using 32 bits instead.

   | Name            | Type                | Params | Mode
-----------------------------------------------------------------
0  | backbone        | Sequential          | 23.5 M | train
1  | classifier      | Sequential          | 38.9 K | train
2  | criterion       | BCEWithLogitsLoss   | 0      | train
3  | train_precision | MultilabelPrecision | 0      | train
4  | train_recall    | MultilabelRecall    | 0      | train
5  | train_f1        | MultilabelF1Score   | 0      | train
6  | train_auroc     | MultilabelAUROC     | 0      | train
7  | val_precision   | MultilabelPrecision | 0      | train
8  | val_recall      | MultilabelRecall    | 0      | train
9  | val_f1          | MultilabelF1Score   | 0      | train
10 | val_auroc       | MultilabelAUROC     | 0      | train
-----------------------------------------------------------------
38.9 K    Trainable params
23.5 M    Non-trainable params
23.5 M    Total params
94.188    Total estimated model params size (MB)
163       Modules in train mode
0         Modules in eval mode
Epoch 0:   1%|‚ñç                                            | 9/842 [00:14<21:46,  0.64it/s, v_num=5ufn, train/loss_step=0.297]
/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: No positive samples in targets, true positive value should be meaningless. Returning zero tensor in true positive score
  warnings.warn(*args, **kwargs)
/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: No negative samples in targets, false positive value should be meaningless. Returning zero tensor in false positive score
  warnings.warn(*args, **kwargs)

Detected KeyboardInterrupt, attempting graceful shutdown ...
Traceback (most recent call last):
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 49, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 598, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1011, in _run
    results = self._run_stage()
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1055, in _run_stage
    self.fit_loop.run()
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 216, in run
    self.advance()
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 458, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 152, in run
    self.advance(data_fetcher)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 348, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 192, in run
    self._optimizer_step(batch_idx, closure)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 270, in _optimizer_step
    call._call_lightning_module_hook(
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 177, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1366, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 154, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 239, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/amp.py", line 79, in optimizer_step
    closure_result = closure()
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 146, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 131, in closure
    step_output = self._step_fn()
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 319, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 329, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 391, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/project/yutianjiang/stmodel/models/baselines/CACo/src/main_bigearthnet.py", line 67, in training_step
    self.train_precision(probs, targets.int())
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torchmetrics/metric.py", line 315, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torchmetrics/metric.py", line 384, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torchmetrics/metric.py", line 549, in wrapped_func
    update(*args, **kwargs)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torchmetrics/classification/stat_scores.py", line 490, in update
    _multilabel_stat_scores_tensor_validation(
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torchmetrics/functional/classification/stat_scores.py", line 664, in _multilabel_stat_scores_tensor_validation
    if check:
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hpc2hdd/home/qwang650/project/yutianjiang/stmodel/models/baselines/CACo/src/main_bigearthnet.py", line 206, in <module>
    trainer.fit(model, datamodule=datamodule)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 560, in fit
    call._call_and_handle_interrupt(
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 62, in _call_and_handle_interrupt
    trainer._teardown()
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1034, in _teardown
    self.strategy.teardown()
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 536, in teardown
    self.lightning_module.cpu()
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/lightning_fabric/utilities/device_dtype_mixin.py", line 82, in cpu
    return super().cpu()
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 964, in cpu
    return self._apply(lambda t: t.cpu())
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 964, in <lambda>
    return self._apply(lambda t: t.cpu())
  File "/hpc2hdd/home/qwang650/anaconda3/envs/caco/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2720478) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
